spring.application.name=spendgrove
spring.datasource.url=jdbc:postgresql://localhost:5432/spendgrove
spring.datasource.username=dev
spring.datasource.password=devpass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true